stages:
  - prepare
  - build
  - deploy

default:
  image: "node:alpine"
  interruptible: true
  tags: [linux, docker]

prepare:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - mv dist/ public/
  artifacts:
    paths:
    - public
